---

- name: Test mirror
  hosts: localhost

  tasks:

    - name: Include OS variables
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: Information
      debug:
        msg: 'Testing {{ repo_release }} repository on {{ openio_repository_mirror_host }}'

    - name: Packages to install
      debug:
        var: sds_pkgs

    # Ensure it is not there
    - name: 'Uninstall OpenIO packages'
      package:
        name: '{{ sds_pkgs }}'
        state: absent

    # Ensure nothing remaining can interfere
    - name: Cleanup repository cache
      command: '{{ clean_all }}'
      args:
        warn: 'no'

    # Setup repositories
    - name: 'Install SDS "stable" repository'
      include_role:
        name: ansible-role-openio-repository
      vars:
        openio_repository_no_log: false
        openio_repository_products:
          sds:
            release: '{{ repo_release.split("/")[0] }}'

    - name: 'Install SDS "unstable" repository'
      include_role:
        name: ansible-role-openio-repository
      vars:
        openio_repository_no_log: false
        openio_repository_products:
          sds:
            release: '{{ repo_release }}'
      when: "'/' in repo.value.release"

    # Try to install
    - name: 'Install OpenIO packages'
      package:
        name: '{{ dep_pkgs + sds_pkgs }}'
        state: latest

    # Display installed versions
    - name: 'Check OpenIO packages versions'
      command: '{{ pkg_info }} {{ " ".join(sds_pkgs) }}'
      register: oio_pkg_info        
      args:
        warn: 'no'

    - name: 'Show OpenIO packages versions'
      debug:
        var: oio_pkg_info

...
